# This Docker Compose file defines three services: frontend, backend, and db.
# 
# Services:
# 
# 1. frontend:
#    - Builds the frontend service from the Dockerfile located in the ./frontend directory.
#    - Maps port 5173 on the host to port 5173 in the container.
#    - Mounts the ./frontend directory to /app in the container.
#    - Ensures the node_modules directory in the container is not overwritten.
#    - Sets the VITE_API_URL environment variable to http://localhost:5000.
#    - Depends on the backend service.
# 
# 2. backend:
#    - Builds the backend service from the Dockerfile located in the ./backend directory.
#    - Maps port 5000 on the host to port 5000 in the container.
#    - Mounts the ./backend directory to /app in the container.
#    - Sets environment variables for database connection (DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD).
#    - Depends on the db service.
# 
# 3. db:
#    - Uses the postgres:16 image to create a PostgreSQL database service.
#    - Maps port 5433 on the host to port 5432 in the container.
#    - Sets environment variables for PostgreSQL configuration (POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD).
#    - Uses a named volume (postgres_data) to persist database data.
# 
# Volumes:
# 
# - postgres_data: A named volume used to persist PostgreSQL data.
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules    # This ensures node_modules from container aren't overwritten
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=flashcards
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=flashcards
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

