version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules    # This ensures node_modules from container aren't overwritten
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=flashcards
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=flashcards
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

